- name: demo on task level variable
  hosts: localhost
  connection: local
  vars:
    COURSE: "Ansible"
    TRAINER: "Sivakumar"
    DURATION: "150hrs"
  tasks:
    - name: print information
      vars:
        COURSE: "DevSecOps with AiOps"
      debug:
        msg: "Hi, I am Learning {{ COURSE }}, Trainer is {{ TRAINER }}, Duration is {{ DURATION }}"