- name: install packages
  hosts: frontend
  connection: local
  tasks:
  - name: install packages
    package:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - httpd
    - firewalld 
    