[frontend]
100.30.230.240 COURSE= "Ansible for NODE 1"

[local]
localhost

 #common inventory variables
[local:vars]       
COURSE="ansible"
TRAINER="Siva"
DURATION="150hrs"

[frontend:vars]       
COURSE="ansible"
TRAINER="Siva"
DURATION="150hrs"